# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

env:
  APP_NAME: 'node'
  COMPONENT_NAME: 'backend'
  RELEASE_PATH: /data/sites/web/ruudjuffermansnl


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm i
    - run: npm run build

    - name: Transfer files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        source: "./build"
        target: ${{ env.RELEASE_PATH }}

    - name: Replace new release
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        script: |
          cd ${{ env.RELEASE_PATH }}
          rm -rf ./www/*
          mv ./build/* ./www
          rm -rf ./build

    - name: Copy config files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        script: |
          echo '${{ secrets.REMOTE_HTACCESS }}' > ${{ env.RELEASE_PATH }}/www/.htaccess